"""Temporal-ordering capability gate.

This is not a headline benchmark. It is the check that runs first, because a model
that cannot report the order of a handful of images cannot be meaningfully scored
on long-video reasoning — any accuracy it posts there would be measuring something
other than temporal understanding.

The gate is deliberately cheap: a few frames of flat colour, one question, exact
string comparison against ground truth generated by ffmpeg. It costs cents and can
save the rest of the sweep.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from av.bench.fixtures import Fixture, fixture_prompt, generate_fixture
from av.bench.receipts import sha256_file
from av.bench.vlm import BenchVLM

_PUNCT = re.compile(r"[^a-z0-9]+")


def normalise_answer(text: str, kind: str) -> list[str]:
    """Turn free-form model output into a comparable ordered list."""
    if not text:
        return []
    # Strip common wrappers before splitting so "Answer: red, blue" parses.
    text = re.sub(r"(?is)^\s*(the\s+)?(answer|order|sequence)\s*(is)?\s*[:\-]\s*", "", text.strip())
    text = text.strip().strip("`").strip()

    if kind in ("count", "motion"):
        return re.findall(r"\d+", text)

    parts = re.split(r"[,\n;]+|\s+->\s+|\s+then\s+", text)
    out: list[str] = []
    for part in parts:
        token = _PUNCT.sub("", part.strip().lower())
        token = re.sub(r"^\d+", "", token)  # drop list numbering like "1red"
        if token:
            out.append(token)
    return out


@dataclass
class OrderingCell:
    n: int
    kind: str
    expected: list[str]
    reported: list[str]
    exact_order: bool
    correct_prefix: int
    n_reported: int
    tokens_in: int | None
    tokens_out: int | None
    ttft_sec: float | None
    wall_sec: float
    ok: bool
    error: str | None = None
    multi_image_unsupported: bool = False
    raw_text: str = ""
    frame_sha256: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "n": self.n,
            "fixture_kind": self.kind,
            "expected": self.expected,
            "reported": self.reported,
            "exact_order": self.exact_order,
            "correct_prefix": self.correct_prefix,
            "n_reported": self.n_reported,
            "tokens_in": self.tokens_in,
            "tokens_out": self.tokens_out,
            "ttft_sec": round(self.ttft_sec, 4) if self.ttft_sec is not None else None,
            "wall_sec": round(self.wall_sec, 4),
            "ok": self.ok,
            "error": self.error,
            "multi_image_unsupported": self.multi_image_unsupported,
            "raw_text": self.raw_text[:2000],
            "frame_sha256": self.frame_sha256,
        }


def score_ordering(expected: list[str], reported: list[str]) -> tuple[bool, int]:
    """Exact-order match, plus how many leading items were right.

    ``correct_prefix`` is what distinguishes "wrong order" from "saw one frame and
    stopped" — the failure mode reported upstream for a six-image colour fixture.
    """
    prefix = 0
    for e, r in zip(expected, reported):
        if e != r:
            break
        prefix += 1
    return (expected == reported), prefix


def run_ordering_cell(vlm: BenchVLM, fixture: Fixture) -> OrderingCell:
    prompt = fixture_prompt(fixture.kind, fixture.n)
    result = vlm.ask(fixture.frame_paths, prompt)
    reported = normalise_answer(result.text, fixture.kind)
    expected = fixture.expected_answer
    exact, prefix = score_ordering(expected, reported)
    return OrderingCell(
        n=fixture.n,
        kind=fixture.kind,
        expected=expected,
        reported=reported,
        exact_order=exact and result.ok,
        correct_prefix=prefix,
        n_reported=len(reported),
        tokens_in=result.tokens_in,
        tokens_out=result.tokens_out,
        ttft_sec=result.ttft_sec,
        wall_sec=result.wall_sec,
        ok=result.ok,
        error=result.error,
        multi_image_unsupported=result.multi_image_unsupported,
        raw_text=result.text,
        frame_sha256=[sha256_file(p) for p in fixture.frame_paths],
    )


def run_gate(
    vlm: BenchVLM,
    *,
    kind: str = "color",
    sizes: tuple[int, ...] = (2, 4, 8),
    work_dir: Path,
    on_cell=None,
) -> tuple[list[OrderingCell], dict]:
    """Run the gate across fixture sizes. Returns cells and a verdict summary."""
    cells: list[OrderingCell] = []
    fixtures: list[Fixture] = []
    for n in sizes:
        fixture = generate_fixture(kind, n, work_dir)
        fixtures.append(fixture)
        cell = run_ordering_cell(vlm, fixture)
        cells.append(cell)
        if on_cell:
            on_cell(cell)

    passed = [c.n for c in cells if c.exact_order]
    failed = [c.n for c in cells if not c.exact_order]
    largest_pass = max(passed) if passed else None

    if any(c.multi_image_unsupported for c in cells):
        verdict = "no_multi_image"
    elif not passed:
        verdict = "fail"
    elif not failed:
        verdict = "pass"
    else:
        verdict = "partial"

    summary = {
        "fixture_kind": kind,
        "sizes": list(sizes),
        "passed_sizes": passed,
        "failed_sizes": failed,
        "largest_passing_n": largest_pass,
        "verdict": verdict,
        "ffmpeg_commands": [c for f in fixtures for c in f.ffmpeg_commands],
    }
    return cells, summary
